### ISSUE TITLE
Does not work with the instructions (1/4/2017)

### ISSUE THREAD

**Issue by Ciantic** [Azure-Samples/app-service-web-nodejs-get-started#1]
I followed these: https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started

And got this instead:

```
git push azure master

Counting objects: 31, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (26/26), done.
Writing objects: 100% (31/31), 5.67 KiB | 0 bytes/s, done.
Total 31 (delta 6), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'c51cbaf447'.
remote: Generating deployment script.
remote: Generating deployment script for node.js Web Site
remote: Generated deployment script files
remote: Running deployment command...
remote: Handling node.js deployment.
remote: Kudu sync from: '/home/site/repository' to: '/home/site/wwwroot'
remote: Copying file: '.gitignore'
remote: Copying file: 'CONTRIBUTING.md'
remote: Copying file: 'LICENSE'
remote: Copying file: 'README.md'
remote: Copying file: 'app.js'
remote: Copying file: 'iisnode.yml'
remote: Copying file: 'package.json'
remote: Ignoring: .git
remote: /opt/npm/3.10.8/node_modules/npm/bin/npm:2
remote: Copying file: 'bin/www'
remote: (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
remote: Copying file: 'public/stylesheets/style.css'
remote:         ^^^^^
remote: Copying file: 'routes/index.js'
remote: SyntaxError: Unexpected identifier
remote: Copying file: 'routes/users.js'
remote:     at Object.exports.runInThisContext (vm.js:76:16)
remote: Copying file: 'views/error.jade'
remote:     at Module._compile (module.js:542:28)
remote: Copying file: 'views/index.jade'
remote:     at Object.Module._extensions..js (module.js:579:10)
remote: Copying file: 'views/layout.jade'
remote:     at Module.load (module.js:487:32)
remote: Using start-up script bin/www from package.json.
remote:     at tryModuleLoad (module.js:446:12)
remote: The package.json file does not specify node.js engine version constraints.
remote:     at Function.Module._load (module.js:438:3)
remote: The node.js application will run with the default node.js version 6.9.3.
remote:     at Module.runMain (module.js:604:10)
remote: Selected npm version null
remote:     at run (bootstrap_node.js:394:7)
remote: One or more of the selected node/npm paths do not exist.
remote:     at startup (bootstrap_node.js:149:9)
remote: An error has occurred during web site deployment.
remote:     at bootstrap_node.js:509:3
remote: npm failed
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://MYSITE.azurewebsites.net/MYSITE.git
 * [new branch]      master -> master
```

**Comment by Ciantic** [comment]
I also tried now with "yo express" example, and got this:

```
git push azure master

Counting objects: 22, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (22/22), 3.35 KiB | 0 bytes/s, done.
Total 22 (delta 2), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'd8edceedf1'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling node.js deployment.
remote: Kudu sync from: '/home/site/repository' to: '/home/site/wwwroot'
remote: Copying file: '.bowerrc'
remote: Copying file: '.editorconfig'
remote: Copying file: '.gitignore'
remote: Copying file: '.yo-rc.json'
remote: Copying file: 'app.js'
remote: Copying file: 'bower.json'
remote: Copying file: 'gulpfile.js'
remote: /opt/npm/3.10.8/node_modules/npm/bin/npm:2
remote: Copying file: 'package.json'
remote: (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
remote: Ignoring: .git
remote:         ^^^^^
remote: Copying file: 'bin/www'
remote: SyntaxError: Unexpected identifier
remote: Copying file: 'public/css/style.css'
remote:     at Object.exports.runInThisContext (vm.js:76:16)
remote: Copying file: 'routes/index.js'
remote:     at Module._compile (module.js:542:28)
remote: Copying file: 'routes/user.js'
remote:     at Object.Module._extensions..js (module.js:579:10)
remote: Copying file: 'views/error.swig'
remote:     at Module.load (module.js:487:32)
remote: Copying file: 'views/index.swig'
remote:     at tryModuleLoad (module.js:446:12)
remote: Copying file: 'views/layout.swig'
remote:     at Function.Module._load (module.js:438:3)
remote: Using start-up script bin/www from package.json.
remote:     at Module.runMain (module.js:604:10)
remote: The package.json file does not specify node.js engine version constraints.
remote:     at run (bootstrap_node.js:394:7)
remote: The node.js application will run with the default node.js version 6.9.3.
remote:     at startup (bootstrap_node.js:149:9)
remote: Selected npm version null
remote:     at bootstrap_node.js:509:3
remote: One or more of the selected node/npm paths do not exist.
remote: An error has occurred during web site deployment.
remote: npm failed
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://MYSITE.azurewebsites.net/MYSITE.git
   c51cbaf..d8edcee  master -> master
```

Something is wrong with the app services.

**Comment by Benjiiim** [comment]
Hi @Ciantic, I have the same issue. Have you been able to solve it?

**Comment by cephalin** [comment]
@Ciantic @Benjiiim This repo is no longer used in our getting started doc. Which doc were you following?

**Comment by Benjiiim** [comment]
I wasn't following the doc, just pushing a fresh express app on Azure App Service and getting the same error. :-(

**Comment by cephalin** [comment]
@Benjiiim It looks like you're running a Linux web app. Linux is in preview right now and has some deployment issues at the moment. I encourage you to log an issue with [https://github.com/projectkudu/kudu](https://github.com/projectkudu/kudu).

**Comment by Ciantic** [comment]
I did get it work, but key was to use the simplest template in Visual Studio (not on the CLI), I think it deployed correctly to Linux web app service.

**Comment by cephalin** [comment]
Yes Linux web app still has some kinks to work out right now.

**Comment by jianghaolu** [comment]
This is happening again since yesterday from our nightly runs:
```
Command: "/home/site/deployments/tools/deploy.sh"
Handling node.js deployment.
Kudu sync from: '/home/site/repository' to: '/home/site/wwwroot'
Copying file: '.gitignore'
Copying file: 'package.json'
Copying file: 'server.js'
Ignoring: .git
Copying file: 'pictures/microsoft_logo.png'
Looking for app.js/server.js under site root.
Using start-up script server.js
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 6.9.1.
Selected npm version null
One or more of the selected node/npm paths do not exist.
/opt/npm/3.10.10/node_modules/npm/bin/npm:2
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
        ^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
An error has occurred during web site deployment.
npm failed
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
/opt/npm/3.10.10/node_modules/npm/bin/npm:2\n(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix\n        ^^^^^\nSyntaxError: Unexpected identifier\n    at createScript (vm.js:56:10)\n    at Object.runInThisContext (vm.js:97:10)\n    at Module._compile (module.js:542:28)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.runMain (module.js:604:10)\n    at run (bootstrap_node.js:393:7)\n    at startup (bootstrap_node.js:150:9)\n/opt/Kudu/bin/Scripts/starter.sh "/home/site/deployments/tools/deploy.sh"
```

**Comment by Benjiiim** [comment]
There have been a lot of changes to Node.js deployment code on App Service on Linux in the past couple weeks that aren’t rolled out yet.
As a workaround, I have been told that the it might be a good idea to specify the node.js version and the npm version you want to use in the package.json and delete the WEBSITE_NODE_DEFAULT_VERSION from your appsettings if you have it.

**Comment by philhack** [comment]
setting this in your ```package.json``` file seems to do the trick when deploying to azure linux web apps:

```
"engines" : { 
	"node" : ">=6.9.3",
	"npm" : "~2.15.9" 	
  }
````

**Comment by Simply007** [comment]
I had also to set the azure web app setting for default node version:
https://blogs.msdn.microsoft.com/azureossds/2018/09/25/how-to-set-node-version-for-windows-node-js-webapp-from-azure-portal/
